import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "@/component/navbar/Navbaradmin";
export const metadata: Metadata = {
  title: "AdminSite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="w-full min-h-screen bg-gradient-to-r bg">
        <div className="flex">
          <Navbar />
        </div>
        <div className="min-h-[calc(100vh)] flex items-center justify-center">
          {children}
        </div>
      </div>
    </>
  );
}
