import type { Metadata } from "next";
import localFont from "next/font/local";
import UserSidebar from "@/component/navbar/Navbaruser";

export const metadata: Metadata = {
  title: "Agoda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full min-h-screen bg-gradient-to-r bg">
      <div className="flex">
        <UserSidebar />
      </div>
      <div className="min-h-[calc(100vh)] flex items-center justify-center">
        {children}
      </div>
    </div>
  );
}
